import type { ReplacementEmployee } from "./types";

export const employees: ReplacementEmployee[] = [
  {
    id: "1",
    name: "Ole Olsen",
    department: "Raud sone",
    position: "Operatør",
    status: "På jobb no",
    available: true,
    workedHours: 32,
    monthlyHours: 146,
    overtime: 8,
  },
  {
    id: "2",
    name: "Maria Hansen",
    department: "Raud sone",
    position: "Operatør",
    status: "Tilgjengeleg",
    available: true,
    workedHours: 28,
    monthlyHours: 140,
    overtime: 2,
  },
  {
    id: "3",
    name: "Lars Johansen",
    department: "Grøn sone",
    position: "Operatør",
    status: "Fråverande",
    available: false,
    workedHours: 18,
    monthlyHours: 91,
    overtime: 0,
  },
  {
    id: "4",
    name: "Anna Berg",
    department: "Pakking",
    position: "Operatør",
    status: "På ferie",
    available: false,
    workedHours: 0,
    monthlyHours: 118,
    overtime: 0,
  },
  {
    id: "5",
    name: "Per Hansen",
    department: "Pakking",
    position: "Operatør",
    status: "Tilgjengeleg",
    available: true,
    workedHours: 37,
    monthlyHours: 154,
    overtime: 12,
  },
];
